name: Build and Publish Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18.9.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.1
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm install

      - name: Run Tests
        run: npm run ci

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Tag
        run: echo "TAG=$(cat package.json | grep '"version":' | awk -F'"' '{print $4; exit;}')" >> $GITHUB_ENV

      - name: Build the Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx create --name shadowfax --use
          DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKER_REPOSITORY }}/react-gold-tsx:latest" -t "${{ secrets.DOCKER_REPOSITORY }}/react-gold-tsx:${TAG}" --push .
